### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jeffwidman** [ixiacom/ATI#1]
I'd like to use https://github.com/ixiacom/ATI/blob/master/Apps/Wireshark%20Dissectors/zab.lua as a starting point for adding a zookeeper dissector into Wireshark... 

The dissector would be bundled by default in Wireshark, so you would benefit as you'd no longer need to maintain a custom dissector, nor fuss with custom installations, and you'd automatically pickup any changes that other folks make to improve the dissector.

However, there's no license on this repo, so I can't use this code... 

Can you add a license?

And (pretty please) make my life easy by using BSD rather than GPL? I'll still happily cite you in the source code comments, it's just if you go with GPL license, then I have to check that the wireshark project is okay with including GPL code, and I personally may opt to just write my own dissector from scratch to skip any GPL headaches down the line.

**Comment by chuckixia** [comment]
License added. MIT.

**Comment by jeffwidman** [comment]
Perfect--thanks!
